In [1]:
import torch
import numpy as np

In [2]:
lista = [[1,2,3],
         [4,5,6]]

tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)

print(arr)
print(arr.dtype)

[[0.09232136 0.10977664 0.38860038 0.38813137]
 [0.71318805 0.76698717 0.61157184 0.31931434]
 [0.81116153 0.27985496 0.82715051 0.24718491]]
float64


In [4]:
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsr = torch.randn(3,3)

print(tns1)
print(tns0)
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[-0.6141,  1.0201,  0.9649],
        [-1.3798, -0.1652,  0.4816],
        [ 0.0716,  0.4583, -0.6595]])


In [5]:
arr = tnsr.data.numpy()

In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
print(tnsr)
tnsr[0, 2] = -10
print('')
print(tnsr)

tensor([[-0.6141,  1.0201,  0.9649],
        [-1.3798, -0.1652,  0.4816],
        [ 0.0716,  0.4583, -0.6595]])

tensor([[ -0.6141,   1.0201, -10.0000],
        [ -1.3798,  -0.1652,   0.4816],
        [  0.0716,   0.4583,  -0.6595]])


In [8]:
print(tnsr[0:2])

tensor([[ -0.6141,   1.0201, -10.0000],
        [ -1.3798,  -0.1652,   0.4816]])


In [9]:
tns = tnsr[0:2, :]
print(tns)
print('')
tnsr = torch.randn(2,3)
print(tnsr)
print('')

print(tns*tnsr)
print('')
print(tns+tnsr)
print('')
print(tns-tnsr)
print('')
print(tns/tnsr)

tensor([[ -0.6141,   1.0201, -10.0000],
        [ -1.3798,  -0.1652,   0.4816]])

tensor([[-0.4284, -0.8206,  0.1091],
        [ 1.6170, -0.0996,  0.4144]])

tensor([[ 0.2631, -0.8371, -1.0909],
        [-2.2311,  0.0164,  0.1995]])

tensor([[-1.0425,  0.1994, -9.8909],
        [ 0.2372, -0.2648,  0.8959]])

tensor([[ -0.1857,   1.8407, -10.1091],
        [ -2.9968,  -0.0657,   0.0672]])

tensor([[  1.4334,  -1.2430, -91.6663],
        [ -0.8533,   1.6594,   1.1622]])


In [10]:
print(tnsr.shape)
print('')
print(tnsr.size())

torch.Size([2, 3])

torch.Size([2, 3])


In [11]:
tns = torch.randn(2,2,3)
print(tns)

tensor([[[ 0.3346,  0.6733, -1.1806],
         [ 0.2905, -0.8753, -0.5845]],

        [[ 0.1939, -2.1258, -0.3763],
         [-1.3194, -0.7786,  1.6075]]])


In [12]:
print(tns.size())
print('')
tns = tns.view(tns.size(0), -1)
print(tns)
print('')
print(tns)

torch.Size([2, 2, 3])

tensor([[ 0.3346,  0.6733, -1.1806,  0.2905, -0.8753, -0.5845],
        [ 0.1939, -2.1258, -0.3763, -1.3194, -0.7786,  1.6075]])

tensor([[ 0.3346,  0.6733, -1.1806,  0.2905, -0.8753, -0.5845],
        [ 0.1939, -2.1258, -0.3763, -1.3194, -0.7786,  1.6075]])


In [13]:
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
   device = torch.device('cpu')

print(device)

cuda


In [14]:
tns = tns.to(device)
print(tns)

tensor([[ 0.3346,  0.6733, -1.1806,  0.2905, -0.8753, -0.5845],
        [ 0.1939, -2.1258, -0.3763, -1.3194, -0.7786,  1.6075]],
       device='cuda:0')
